In [1]:
import numpy as np

In [2]:
# 1차원 배열 생성
python_list = [1, 2, 3, 4, 5]
np_array_1d = np.array(python_list)

print(f"파이썬 리스트: {python_list}")
print(f"NumPy 1차원 배열: {np_array_1d}")
print(f"배열의 타입: {type(np_array_1d)}")

파이썬 리스트: [1, 2, 3, 4, 5]
NumPy 1차원 배열: [1 2 3 4 5]
배열의 타입: <class 'numpy.ndarray'>


In [3]:
# 2차원 배열 (행렬) 생성
python_list_2d = [[1, 2, 3], [4, 5, 6]]
np_array_2d = np.array(python_list_2d)

print("\nNumPy 2차원 배열:")
print(np_array_2d)


NumPy 2차원 배열:
[[1 2 3]
 [4 5 6]]


In [4]:
# 1차원 배열의 속성
print(f"\n1D 배열 차원: {np_array_1d.ndim}")   # 출력: 1
print(f"1D 배열 형태: {np_array_1d.shape}") # 출력: (5,)
print(f"1D 배열 타입: {np_array_1d.dtype}") # 출력: int32 또는 int64


1D 배열 차원: 1
1D 배열 형태: (5,)
1D 배열 타입: int64


In [5]:
# 2차원 배열의 속성
print(f"\n2D 배열 차원: {np_array_2d.ndim}")   # 출력: 2
print(f"2D 배열 형태: {np_array_2d.shape}") # 출력: (2, 3) -> 2행 3열
print(f"2D 배열 타입: {np_array_2d.dtype}") # 출력: int32 또는 int64


2D 배열 차원: 2
2D 배열 형태: (2, 3)
2D 배열 타입: int64


In [6]:
# 0으로 채워진 3x4 배열 생성
zeros_arr = np.zeros((3, 4))
print("0으로 채워진 배열:\n", zeros_arr)

0으로 채워진 배열:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# 1로 채워진 2x3 배열 생성
ones_arr = np.ones((2, 3))
print("\n1로 채워진 배열:\n", ones_arr)


1로 채워진 배열:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 0부터 9까지의 숫자로 배열 생성 (파이썬의 range와 유사)
range_arr = np.arange(10)
print("\narange를 이용한 배열:", range_arr)


arange를 이용한 배열: [0 1 2 3 4 5 6 7 8 9]


In [9]:
# 2부터 10까지 2씩 증가하는 숫자로 배열 생성
step_arr = np.arange(2, 11, 2)
print("\nstep이 있는 arange 배열:", step_arr)


step이 있는 arange 배열: [ 2  4  6  8 10]


In [10]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

In [11]:
# 덧셈
print("덧셈:", arr1 + arr2)  # 출력: [ 6  8 10 12]

덧셈: [ 6  8 10 12]


In [13]:
# 뺄셈
print("뺄셈:", arr2 - arr1)  # 출력: [4 4 4 4]

뺄셈: [4 4 4 4]


In [14]:
# 곱셈
print("곱셈:", arr1 * arr2)  # 출력: [ 5 12 21 32]

곱셈: [ 5 12 21 32]


In [15]:
# 나눗셈
print("나눗셈:", arr2 / arr1)  # 출력: [5.  3.  2.333... 2. ]

나눗셈: [5.         3.         2.33333333 2.        ]


In [16]:
# 스칼라(단일 값) 연산
print("\n스칼라 곱셈:", arr1 * 10) # 출력: [10 20 30 40]
print("스칼라 덧셈:", arr1 + 5) # 출력: [6 7 8 9]


스칼라 곱셈: [10 20 30 40]
스칼라 덧셈: [6 7 8 9]


In [17]:
# 2차원 배열 인덱싱/슬라이싱
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [18]:
# 2행 3열의 원소 (0부터 시작)
print("\n2행 3열의 원소:", arr2d[1, 2]) # 출력: 6


2행 3열의 원소: 6


In [19]:
# 첫 번째 행 전체 가져오기
print("첫 번째 행:", arr2d[0, :]) # 출력: [1 2 3]

첫 번째 행: [1 2 3]


In [20]:
# 두 번째 열 전체 가져오기
print("두 번째 열:", arr2d[:, 1]) # 출력: [2 5 8]

두 번째 열: [2 5 8]


In [22]:
# NumPy는 합계, 평균, 표준편차 등 기본적인 통계 함수를 쉽게 계산
data = np.array([[1, 2, 3], [4, 5, 6]])

In [23]:
# 전체 합계
print("전체 합계:", np.sum(data)) # 출력: 21

전체 합계: 21


In [24]:
# 전체 평균
print("전체 평균:", np.mean(data)) # 출력: 3.5

전체 평균: 3.5


In [25]:
# 각 열(column)의 합계 (axis=0)
print("각 열의 합계:", np.sum(data, axis=0)) # 출력: [5 7 9]

각 열의 합계: [5 7 9]


In [26]:
# 각 행(row)의 합계 (axis=1)
print("각 행의 합계:", np.sum(data, axis=1)) # 출력: [ 6 15]

각 행의 합계: [ 6 15]


In [27]:
# 최대값, 최소값
print("최대값:", np.max(data)) # 출력: 6
print("최소값:", np.min(data)) # 출력: 1

최대값: 6
최소값: 1
