In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1차원 NumPy 배열 생성
np_arr_1d = np.arange(1, 6)
print("1D NumPy 배열:\n", np_arr_1d)

1D NumPy 배열:
 [1 2 3 4 5]


In [3]:
# NumPy 배열로 Pandas Series 만들기
pd_series = pd.Series(np_arr_1d, name='MyNumbers')
print("\nPandas Series:\n", pd_series)
print("-" * 30)


Pandas Series:
 0    1
1    2
2    3
3    4
4    5
Name: MyNumbers, dtype: int64
------------------------------


In [4]:
# 2차원 NumPy 배열 생성
np_arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D NumPy 배열:\n", np_arr_2d)

2D NumPy 배열:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# NumPy 배열로 Pandas DataFrame 만들기
# 컬럼 이름을 지정해주면 더 의미있는 데이터 구조가 됩니다.
pd_df = pd.DataFrame(np_arr_2d, columns=['A', 'B', 'C'])
print("\nPandas DataFrame:\n", pd_df)


Pandas DataFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [6]:
# DataFrame을 다시 NumPy 배열로 변환
# .to_numpy() 사용을 권장합니다.
numpy_from_df = pd_df.to_numpy()
print("DataFrame에서 변환된 NumPy 배열:\n", numpy_from_df)
print("\n변환된 배열의 타입:", type(numpy_from_df))

DataFrame에서 변환된 NumPy 배열:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

변환된 배열의 타입: <class 'numpy.ndarray'>


In [7]:
# Series도 마찬가지입니다.
numpy_from_series = pd_series.to_numpy()
print("\nSeries에서 변환된 NumPy 배열:", numpy_from_series)


Series에서 변환된 NumPy 배열: [1 2 3 4 5]


In [8]:
data = {'A': [1, 4, 9, 16],
        'B': [10, 20, 30, 40],
        'C': [100, 400, 900, 1600]}
df = pd.DataFrame(data)
print("원본 DataFrame:\n", df)

원본 DataFrame:
     A   B     C
0   1  10   100
1   4  20   400
2   9  30   900
3  16  40  1600


In [9]:
# DataFrame 전체에 np.sqrt (제곱근) 함수 적용
df_sqrt = np.sqrt(df)
print("\n제곱근 계산 후 DataFrame:\n", df_sqrt)


제곱근 계산 후 DataFrame:
      A         B     C
0  1.0  3.162278  10.0
1  2.0  4.472136  20.0
2  3.0  5.477226  30.0
3  4.0  6.324555  40.0


In [10]:
# 특정 열(Series)에 np.log (자연로그) 함수 적용
log_of_B = np.log(df['B'])
print("\n'B' 열에 로그 계산:\n", log_of_B)


'B' 열에 로그 계산:
 0    2.302585
1    2.995732
2    3.401197
3    3.688879
Name: B, dtype: float64


In [11]:
# NumPy의 np.where() 함수를 사용하면 Pandas DataFrame에서 특정 조건에 따라 값을 효율적으로 변경.
# np.where(condition, value_if_true, value_if_false) 형태로 사용
# 학생들의 점수 데이터가 담긴 DataFrame 생성
scores_df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'score': [88, 45, 95, 60, 75]
})
print("원본 점수 DataFrame:\n", scores_df)

원본 점수 DataFrame:
       name  score
0    Alice     88
1      Bob     45
2  Charlie     95
3    David     60
4      Eve     75


In [12]:
# 점수가 70점 이상이면 'Pass', 미만이면 'Fail'을 부여하는 'Result' 열 추가
# scores_df['score'] >= 70 이라는 Pandas 조건식을 np.where에 바로 사용 가능
scores_df['Result'] = np.where(scores_df['score'] >= 70, 'Pass', 'Fail')
print("\n결과가 추가된 DataFrame:\n", scores_df)


결과가 추가된 DataFrame:
       name  score Result
0    Alice     88   Pass
1      Bob     45   Fail
2  Charlie     95   Pass
3    David     60   Fail
4      Eve     75   Pass
